import NavigationMap from '../../interfaces/NavigationMap';

const navigationMap: NavigationMap = {
  PartyScatta: {
    currentSrc: 'client-projects/partyscatta',
    previousSrc: 'client-projects/mikes-world',
    previousTitle: `Mike's World`,
    nextSrc: 'client-projects/higher-education',
    nextTitle: 'Higher Education',
    navColour: 'bg-red-600',
  },
  HigherEducation: {
    currentSrc: 'client-projects/higher-education',
    previousSrc: 'client-projects/partyscatta',
    previousTitle: 'PARTYSCATTA',
    nextSrc: 'client-projects/dolore',
    nextTitle: 'Dolore',
    navColour: 'bg-orangutan',
  },
  Dolore: {
    currentSrc: 'client-projects/dolore',
    previousSrc: 'client-projects/higher-education',
    previousTitle: 'Higher Education',
    nextSrc: 'client-projects/jaiye',
    nextTitle: 'Jaiye',
    navColour: 'bg-emerald-400',
  },
  Jaiye: {
    currentSrc: 'client-projects/jaiye',
    previousSrc: 'client-projects/dolore',
    previousTitle: 'Dolore',
    nextSrc: 'client-projects/psychoyp',
    nextTitle: 'PsychoYP',
    navColour: 'bg-green-500',
  },
  PsychoYP: {
    currentSrc: 'client-projects/psychoyp',
    previousSrc: 'client-projects/jaiye',
    previousTitle: 'Jaiye',
    nextSrc: 'client-projects/see-gbedu',
    nextTitle: 'See Gbedu',
    navColour: 'bg-[#c5a554]',
  },
  SeeGbedu: {
    currentSrc: 'client-projects/see-gbedu',
    previousSrc: 'client-projects/psychoyp',
    previousTitle: 'PsychoYP',
    nextSrc: 'client-projects/crown-bounce',
    nextTitle: 'Crown Bounce',
    navColour: 'bg-fuchsia-500',
  },
  CrownBounce: {
    currentSrc: 'client-projects/crown-bounce',
    previousSrc: 'client-projects/see-gbedu',
    previousTitle: 'See Gbedu',
    nextSrc: 'client-projects/menace-talk',
    nextTitle: 'Menace Talk',
    navColour: 'bg-[#c5a554]',
  },
  MenaceTalk: {
    currentSrc: 'client-projects/menace-talk',
    previousSrc: 'client-projects/crown-bounce',
    previousTitle: 'Crown Bounce',
    nextSrc: 'client-projects/ye-anthem',
    nextTitle: 'Ye Anthem',
    navColour: 'bg-pink-500',
  },
  YeAnthem: {
    currentSrc: 'client-projects/ye-anthem',
    previousSrc: 'client-projects/menace-talk',
    previousTitle: 'Menace Talk',
    nextSrc: 'client-projects/nuniverse',
    nextTitle: 'NüNiverse',
    navColour: 'bg-blue-500',
  },
  Nuniverse: {
    currentSrc: 'client-projects/nuniverse',
    previousSrc: 'client-projects/ye-anthem',
    previousTitle: 'Ye Anthem',
    nextSrc: 'client-projects/family',
    nextTitle: 'Family',
    navColour: 'bg-blue-500',
  },
  Family: {
    currentSrc: 'client-projects/family',
    previousSrc: 'client-projects/nuniverse',
    previousTitle: 'NüNiverse',
    nextSrc: 'client-projects/popwave',
    nextTitle: 'Popwave',
    navColour: 'bg-sky-500',
  },
  Popwave: {
    currentSrc: 'client-projects/popwave',
    previousSrc: 'client-projects/family',
    previousTitle: 'Family',
    nextSrc: 'client-projects/mikes-world',
    nextTitle: `Mike's World`,
    navColour: 'bg-green-600',
  },
  MikesWrld: {
    currentSrc: 'client-projects/mikes-world',
    previousSrc: 'client-projects/popwave',
    previousTitle: 'Popwave',
    nextSrc: 'client-projects/partyscatta',
    nextTitle: 'PARTYSCATTA',
    navColour: 'bg-orange-600',
  },
};

export default navigationMap;
